### ISSUE TITLE
给个java版本

### ISSUE THREAD

**Issue by Chenshuai770** [amap-demo/iOS-cluster-marker#11]
给个android 版本

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
android 版本参见：  https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
android 版本参加  https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
android 版本参加  https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
android 版本参加  https://github.com/amap-demo/android-cluster-marker

**Comment by broad3** [comment]
android 版本参加  https://github.com/amap-demo/android-cluster-marker
